import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("api/shopify/products", "routes/api.shopify.products.tsx"),
  route("api/shopify/variants", "routes/api.shopify.variants.tsx"),
  route("api/line-items/:id/link", "routes/api.line-items.$id.link.tsx"),
  route("api/sync", "routes/api.sync.tsx"),
  route("api/sync/debug", "routes/api.sync.debug.tsx"),
  route("api/sync/reset", "routes/api.sync.reset.tsx"),
  route("invoices/:id/receiving-summary", "routes/invoices.$id.receiving-summary.tsx"),
  route("credits/:id/summary", "routes/credits.$id.summary.tsx"),
  layout("routes/app.tsx", [
    route("dashboard", "routes/dashboard.tsx"),
    route("products", "routes/products.tsx"),
    route("products/:id", "routes/products.$id.tsx"),
    route("invoices", "routes/invoices.tsx"),
    route("invoices/upload", "routes/invoices.upload.tsx"),
    route("invoices/:id", "routes/invoices.$id.tsx"),
    route("invoices/:id/edit", "routes/invoices.$id.edit.tsx"),
    route("invoices/:id/receive", "routes/invoices.$id.receive.tsx"),
    route("suppliers", "routes/suppliers.tsx"),
    route("suppliers/new", "routes/suppliers.new.tsx"),
    route("suppliers/:id", "routes/suppliers.$id.tsx"),
    route("vendors", "routes/vendors.tsx"),
    route("vendors/new", "routes/vendors.new.tsx"),
    route("vendors/:id", "routes/vendors.$id.tsx"),
    route("credits", "routes/credits.tsx"),
    route("credits/:id", "routes/credits.$id.tsx"),
    route("users", "routes/users.tsx"),
    route("failures", "routes/failures.tsx"),
    route("audit", "routes/audit.tsx"),
    route("reports", "routes/reports.tsx"),
    route("reports/margins", "routes/reports.margins.tsx"),
    route("reports/vendor-performance", "routes/reports.vendor-performance.tsx"),
    route("reports/inventory-valuation", "routes/reports.inventory-valuation.tsx"),
    route("reports/spend-analysis", "routes/reports.spend-analysis.tsx"),
    route("reports/sales-velocity", "routes/reports.sales-velocity.tsx"),
    route("reports/receiving-history", "routes/reports.receiving-history.tsx"),
    route("settings", "routes/settings.tsx"),
    route("settings/po-import", "routes/settings.po-import.tsx"),
  ]),
] satisfies RouteConfig;
